#!/bin/sh

vim -b --clean -c 'set modified' --cmd "set buftype=acwrite" \
        --cmd "autocmd BufWriteCmd * :call writefile(split(getreg('0', 1), '\n', 1), getreg('%'), 'wb') | set nomodified" "$@"
